service: travel-app-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
